CREATE VIEW numSecuelas
AS SELECT TITULO_LINK, ESTRENO_LINK, COUNT(*) AS NUM_SECUELAS
FROM secuelasM
GROUP BY TITULO_LINK, ESTRENO_LINK;


CREATE VIEW maxSecuelas
AS SELECT TITULO_LINK AS TITULO, n.ESTRENO_LINK AS ESTRENO, n.NUM_SECUELAS AS NUMERO_DE_SECUELAS
FROM numSecuelas n
WHERE n.NUM_SECUELAS IN (SELECT MAX(NUM_SECUELAS) FROM numSecuelas s);

SELECT * FROM maxSecuelas;

SELECT DISTINCT s.TITULO, s.ESTRENO
FROM maxSecuelas m, secuelasM s
WHERE s.TITULO_LINK = m.TITULO
ORDER BY s.ESTRENO ASC;


EXPLAIN PLAN FOR SELECT DISTINCT s.TITULO, s.ESTRENO
FROM maxSecuelas m, secuelasM s
WHERE s.TITULO_LINK = m.TITULO
ORDER BY s.ESTRENO ASC;

SELECT PLAN_TABLE_OUTPUT FROM TABLE(DBMS_XPLAN.DISPLAY());

DROP VIEW numSecuelas;
DROP VIEW maxSecuelas;