-- Asignatura: Bases de Datos
-- Autores: Diego Mateo Lorente  --- 873338
--          Carlos Solana Melero --- 872815
--          Daniel Sim�n Gay�n   --- 870984


CREATE TABLE Produccion (
    TITULO VARCHAR(200) ,
    ESTRENO NUMBER,
    TIPO VARCHAR(32) CHECK (TIPO IN ('movie', 'tv series', 'episode')),
    PRIMARY KEY(TITULO, ESTRENO, TIPO)
)
--PARTITION BY LIST (TIPO)
--(
--    PARTITION movies VALUES ('movie'),
--    PARTITION others VALUES (DEFAULT)
--);



CREATE TABLE Genero (
    TITULO VARCHAR(200),
    ESTRENO NUMBER,
    GENERO VARCHAR(32),
    TIPO VARCHAR(32),
    PRIMARY KEY (TITULO,ESTRENO,TIPO, GENERO),
    FOREIGN KEY (TITULO,ESTRENO,TIPO) REFERENCES Produccion(TITULO,ESTRENO,TIPO)
);

CREATE TABLE Pelicula (
    TITULO VARCHAR(200),
    ESTRENO NUMBER CHECK (ESTRENO BETWEEN 1895 AND 2024),
    TIPO VARCHAR(32),
    PRIMARY KEY (TITULO, ESTRENO, TIPO),
    FOREIGN KEY (TITULO, ESTRENO, TIPO) REFERENCES Produccion(TITULO, ESTRENO, TIPO)
);
--PARTITION BY RANGE (ESTRENO) (
--    PARTITION p_before_1980 VALUES LESS THAN (1980),
--    PARTITION p_1980_to_2010 VALUES LESS THAN (2011),
--    PARTITION p_after_2010 VALUES LESS THAN (MAXVALUE)
--);


CREATE TABLE Link (
    TITULO VARCHAR(200),
    ESTRENO NUMBER,
    TITULO_LINK VARCHAR(200),
    ESTRENO_LINK NUMBER,
    LINK VARCHAR(32),
    TIPO VARCHAR(32),
    PRIMARY KEY (TITULO,ESTRENO,TIPO,LINK,TITULO_LINK,ESTRENO_LINK),
    FOREIGN KEY (TITULO,ESTRENO,TIPO) REFERENCES Pelicula(TITULO,ESTRENO,TIPO),
    FOREIGN KEY (TITULO_LINK,ESTRENO_LINK,TIPO) REFERENCES Pelicula(TITULO,ESTRENO,TIPO)
);





CREATE TABLE Serie (
    TITULO VARCHAR(200),
    ESTRENO NUMBER,
    PERIODO_EMISION VARCHAR(32),
    TIPO VARCHAR(32),
    PRIMARY KEY (TITULO, ESTRENO, TIPO), 
    FOREIGN KEY (TITULO, ESTRENO, TIPO) REFERENCES Produccion(TITULO, ESTRENO,TIPO) 
);

CREATE TABLE Capitulo (
    TITULO_SERIE VARCHAR(200),
    TEMPORADA NUMBER(9),
    NUMERO_CAPITULO NUMBER(9),
    TITULO VARCHAR(200),
    ESTRENO NUMBER,
    TIPO VARCHAR(32),
    ESTRENO_SERIE NUMBER,
    TIPO_SERIE VARCHAR(32),
    PRIMARY KEY (TITULO, TITULO_SERIE, ESTRENO, TIPO, ESTRENO_SERIE, TIPO_SERIE),
    FOREIGN KEY (TITULO_SERIE, ESTRENO_SERIE, TIPO_SERIE ) REFERENCES Serie(TITULO, ESTRENO, TIPO),
    FOREIGN KEY (TITULO, ESTRENO,TIPO) REFERENCES Produccion(TITULO, ESTRENO,TIPO) 
);

CREATE TABLE LugarNacimiento(
    LUGAR_NACIMIENTO VARCHAR(150) PRIMARY KEY,
    NACIONALIDAD VARCHAR(100)
);


CREATE TABLE Persona (
    SEXO VARCHAR(2) CHECK (SEXO IN ('f', 'm', '')),
    LUGAR_NACIMIENTO VARCHAR(150),
    NOMBRE VARCHAR(100) NOT NULL,
    ID VARCHAR(32) PRIMARY KEY,
    FOREIGN KEY (LUGAR_NACIMIENTO) REFERENCES LugarNacimiento(LUGAR_NACIMIENTO)
);

CREATE TABLE Trabaja (
    PAPEL VARCHAR(32),
    ID VARCHAR(32),
    ESTRENO NUMBER,
    TITULO VARCHAR(200),
    TIPO VARCHAR(32),
    PRIMARY KEY (PAPEL, ID, ESTRENO, TITULO, TIPO)
);



CREATE TABLE InfoPersonaje (
    PERSONAJE VARCHAR(100),
    IMPORTANCIA FLOAT,
    PAPEL VARCHAR(32),
    ID VARCHAR(32),
    ESTRENO NUMBER,
    TITULO VARCHAR(200), 
    TIPO VARCHAR(32),
    PRIMARY KEY (PAPEL,ID,ESTRENO,TITULO,TIPO, PERSONAJE),
    FOREIGN KEY (PAPEL,ID,ESTRENO,TITULO,TIPO) REFERENCES Trabaja (PAPEL,ID,ESTRENO,TITULO,TIPO)
);