-- Asignatura: Bases de Datos
-- Autores: Diego Mateo Lorente  --- 873338
--          Carlos Solana Melero --- 872815
--          Daniel Simón Gayán   --- 870984


-- Crear la tabla Liga
CREATE TABLE Liga (
 DIVISION CHAR(32) PRIMARY KEY
);

-- Crear la tabla Temporada
CREATE TABLE Temporada (
 INICIO_TEMPORADA CHAR(32),
 FIN_TEMPORADA CHAR(32) NOT NULL,
 DIVISION CHAR(32),
 PRIMARY KEY (INICIO_TEMPORADA, DIVISION),
 FOREIGN KEY (DIVISION) REFERENCES Liga(DIVISION)
);

-- Crear la tabla Jornada
CREATE TABLE Jornada (
 INICIO_TEMPORADA CHAR(32),
 JORNADA NUMBER,
 DIVISION CHAR(32),
 PRIMARY KEY (JORNADA, INICIO_TEMPORADA, DIVISION),
 FOREIGN KEY (INICIO_TEMPORADA, DIVISION) REFERENCES Temporada(INICIO_TEMPORADA, DIVISION),
 CONSTRAINT cons_jornada CHECK (JORNADA >= 0)
);

-- Crear la tabla Estadio
CREATE TABLE Estadio (
 ESTADIO CHAR(50),
 FECHA_INAG CHAR(32),
 AFORO CHAR(32),
 PRIMARY KEY (ESTADIO),
 CONSTRAINT cons_afo CHECK (AFORO >= 0)
);

-- Crear la tabla Equipo
CREATE TABLE Equipo (
 NOMBRE_EQUIPO CHAR(50),
 NOMBRE_OFICIAL CHAR(50),
 CIUDAD CHAR(32),
 FUNDACION CHAR(32), 
 FUNDACION_LEGAL CHAR(32),
 NOMBRE_HISTORICO CHAR(50),
 ESTADIO CHAR(50),
 PRIMARY KEY (NOMBRE_EQUIPO), 
 FOREIGN KEY (ESTADIO) REFERENCES Estadio(ESTADIO)
);

-- Crear la tabla Nombres
CREATE TABLE Nombres (
 NOMBRE_EQUIPO CHAR(50) NOT NULL,
 OTRO_NOMBRE CHAR(36) PRIMARY KEY,
 FOREIGN KEY (NOMBRE_EQUIPO) REFERENCES Equipo(NOMBRE_EQUIPO)
);

-- Crear la tabla Partido
CREATE TABLE Partido (
 ID NUMBER PRIMARY KEY,
 INICIO_TEMPORADA CHAR(32),
 DIVISION CHAR(32),
 JORNADA NUMBER,
 EQUIPO_LOCAL CHAR(50) NOT NULL,
 EQUIPO_VISITANTE CHAR(50) NOT NULL,
 GOLES_LOCAL NUMBER(2) NOT NULL,
 GOLES_VISITANTE NUMBER(2) NOT NULL,
 CONSTRAINT cons_gLocal CHECK (GOLES_LOCAL >= 0),
 CONSTRAINT cons_gVisitante CHECK (GOLES_VISITANTE >= 0),
 FOREIGN KEY (EQUIPO_LOCAL) REFERENCES Equipo(NOMBRE_EQUIPO),
 FOREIGN KEY (EQUIPO_VISITANTE) REFERENCES Equipo(NOMBRE_EQUIPO),
 FOREIGN KEY (INICIO_TEMPORADA,DIVISION,JORNADA) REFERENCES Jornada(INICIO_TEMPORADA,DIVISION,JORNADA)
);






















