-- Asignatura: Bases de Datos
-- Autores: Diego Mateo Lorente  --- 873338
--          Carlos Solana Melero --- 872815
--          Daniel Simón Gayán   --- 870984


-- Poblar la tabla Liga
INSERT INTO Liga SELECT DISTINCT DIVISION
	FROM datosdb.ligahost
	WHERE DIVISION IS NOT NULL;

-- Poblar la tabla Temporada 
INSERT INTO Temporada SELECT DISTINCT INICIO_TEMPORADA, FIN_TEMPORADA,  DIVISION  
	FROM datosdb.ligahost
	WHERE INICIO_TEMPORADA IS NOT NULL AND DIVISION IS NOT NULL AND FIN_TEMPORADA IS NOT NULL;

-- Poblar la tabla Jornada 
INSERT INTO Jornada SELECT DISTINCT INICIO_TEMPORADA, JORNADA,  DIVISION  
	FROM datosdb.ligahost
	WHERE INICIO_TEMPORADA IS NOT NULL AND DIVISION IS NOT NULL AND JORNADA IS NOT NULL;
 
-- Poblar la tabla Estadio 
INSERT INTO Estadio SELECT DISTINCT ESTADIO, FECHA_INAG, AFORO  
	FROM datosdb.ligahost
	WHERE ESTADIO IS NOT NULL;
 
-- Poblar la tabla Equipo 
INSERT INTO Equipo SELECT DISTINCT EQUIPO_LOCAL, Club , CIUDAD, FUNDACION , Fund_legal, Nombre , ESTADIO   
	FROM datosdb.ligahost
	WHERE EQUIPO_LOCAL IS NOT NULL;
 
-- Poblar la tabla Nombres 
 INSERT INTO Nombres SELECT DISTINCT EQUIPO_LOCAL, EQUIPO
	FROM datosdb.ligahost
  WHERE EQUIPO IS NOT NULL AND EQUIPO_LOCAL IS NOT NULL;
 
-- Crear la secuencia sec 
 CREATE SEQUENCE sec START WITH 1 INCREMENT BY 1;

-- Poblar la tabla Partido 
 INSERT INTO Partido (ID,INICIO_TEMPORADA, DIVISION, JORNADA, EQUIPO_LOCAL, EQUIPO_VISITANTE, GOLES_LOCAL, GOLES_VISITANTE)
 SELECT   sec.NEXTVAL,
         INICIO_TEMPORADA, 
         DIVISION, 
         JORNADA, 
         EQUIPO_LOCAL, 
         EQUIPO_VISITANTE, 
         GOLES_LOCAL, 
         GOLES_VISITANTE
 FROM datosdb.ligahost
	WHERE INICIO_TEMPORADA IS NOT NULL AND DIVISION IS NOT NULL AND JORNADA IS NOT NULL AND EQUIPO_LOCAL IS NOT NULL AND EQUIPO_VISITANTE IS NOT NULL AND GOLES_LOCAL IS NOT NULL AND GOLES_VISITANTE IS NOT NULL;