all: practica_3

practica_3: instante.hpp periodo.hpp actividad.hpp coleccionSeg.hpp practica_3.cpp
		g++ practica_3.cpp instante.cpp periodo.cpp actividad.cpp coleccionSeg.hpp -o practica_3 -std=c++11

clean:
		/bin/rm -f practica_3
